version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always

  db:
    env_file:
      - config/.env.local
    image: postgres:latest
    ports:
      - "5432:5432"
#    volumes:
#      - /postgres-data:/var/lib/postgresql/data

  redis:
    image: "redis"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    depends_on:
      - web

  celery_worker:
    container_name: celery_worker
    build: .
    command:  celery -A celery_worker worker -B --loglevel=info
    volumes:
      - .:/app
    env_file:
      - config/.env.local
    depends_on:
      - web
      - redis
