version: '3'

services:
  web:
    build: .  # Путь к директории с вашим FastAPI приложением
    ports:
      - "8000:8000"  # Проброс портов - порт FastAPI приложения в контейнере и порт хоста
    depends_on:
      - db  # Указание на то, что этот сервис зависит от сервиса "db"

  db:
    image: postgres:latest  # Используем образ PostgreSQL
    environment:
      POSTGRES_USER: myuser  # Имя пользователя PostgreSQL
      POSTGRES_PASSWORD: mypassword  # Пароль пользователя PostgreSQL
      POSTGRES_DB: mydatabase  # Имя базы данных PostgreSQL